language: go
sudo: false
go:
  - 1.4
  - 1.5
  - 1.6
  - tip
install:
  - go get "github.com/spf13/cobra"
  - go get "github.com/spf13/viper"
  - go get "github.com/tarm/serial"
  - go get "github.com/inconshreveable/mousetrap"
script:
  - make
  - make cross
notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
