language: go
sudo: false
go:
#  - 1.4
#  - 1.5
  - 1.6
#  - tip
env:
#  - GIMME_OS=linux GIMME_ARCH=arm
  - GIMME_OS=linux GIMME_ARCH=386
#  - GIMME_OS=darwin GIMME_ARCH=amd64
#  - GIMME_OS=windows GIMME_ARCH=386
install:
  - go get "github.com/spf13/cobra"
  - go get "github.com/spf13/viper"
  - go get "github.com/tarm/serial"
  - go get "github.com/inconshreveable/mousetrap"
script:
  - go build -v
  - wmc config
notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
